version: '3.8'

services:
  book:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nest-graphql-book
    command: pnpm run start:dev
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
    networks:
      - book-api-network

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=book
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - book-api-network

networks:
  book-api-network:
    driver: bridge

volumes:
  postgresql-data:
    driver: local
